### ISSUE TITLE
`NOT IN` precedence issues

### ISSUE THREAD

**Issue by matthias-Q** [DerekStride/tree-sitter-sql#128]
As discussed in #126 `NOT IN` is currently not implemented

**Comment by DerekStride** [comment]
## Additional context

Implementing `NOT IN` as mentioned in #126, is causing some errors with precedence. I think the root cause might be from the between expression added in #117. It has a rule `seq($._expression, $.keyword_and, $._expression)` but the `binary_expression` node is also defined as `seq($._expression, $.keyword_and, $._expression)`.

Some investigation & work is required to detangle the precedence issues and implement `NOT IN`.
