### ISSUE TITLE
Other parser implementations

### ISSUE THREAD

**Issue by m-novikov** [DerekStride/tree-sitter-sql#18]
I didn't see your project when I started my parser implementation https://github.com/m-novikov/tree-sitter-sql
I added you to the readme, but maybe we should join forces somehow :)

**Comment by dmfay** [comment]
There's also [tjdevries/tree-sitter-sql](https://github.com/tjdevries/tree-sitter-sql) and [tk-shirasaka/tree-sitter-sql](https://github.com/tk-shirasaka/tree-sitter-sql) that I know of.

**Comment by DerekStride** [comment]
> On future plans I do think it'd be good to talk with the maintainers of other tree-sitter-sql projects -- maybe we could set up a chatroom of some sort so everyone doesn't have to coordinate right off the bat? There's still no official binding and it'd be nice to consolidate our various efforts and get that process started.

Great idea!

Also, sorry for the late reply here @m-novikov, I'd be happy to add a list of other implementations. I think the suggestion from @dmfay to consolidate our efforts makes a lot of sense. I'm open to suggestions and ideas on how to do this. In the meantime I can set up a chatroom (e.g. discord, slack, etc) add a link to the readme. I'll also invite other maintainers to join the conversation.

If the chatroom is desired leave a 👍 on this comment and I'll set that up.

**Comment by FFengIll** [comment]
I am sure tree-sitter is good.
But for sql, the kinds of dialects could be a large challenge.

I wanna provide a ref for help (more or less) : https://github.com/AlecStrong/sql-psi
Look forward to the solution with tree-sitter ~

**Comment by aharpervc** [comment]
What's a good strategy to have multiple SQL variants live side by side in a single repo... and is such a thing even realistic? For example, maybe it's better that pg sql & sqlite are distinct grammars/repos.

I'm also think about this from the perspective of making an mssql grammar. I don't necessarily think it'd be useful to open a PR for that to any of these repos. Perhaps a forking to tree-sitter-mssql and making the adjustments there would be preferable.

**Comment by dmfay** [comment]
> What's a good strategy to have multiple SQL variants live side by side in a single repo... and is such a thing even realistic? For example, maybe it's better that pg sql & sqlite are distinct grammars/repos.

I can't speak for anyone else but I don't think it's unrealistic as such. It's a good question and might not have an easy answer.

Languages are always moving targets (some faster than others), and tree-sitter grammars seem to be generally descriptive rather than prescriptive; Postgres won't be replacing libpg_query with tree-sitter any time soon. But in most cases, language changes/differences are purely additive. For example, a Python grammar would support the pattern matching introduced in Python 3.10 whether or not you yourself have upgraded to it yet. It'd highlight or pass or what have you code with pattern matching that would blow up in your 3.9 interpreter, and that's your problem not the grammar's.

SQL dialects however have intra-family incompatibilities like the standard `LIMIT` at the end vs T-SQL's `TOP` up front. A permissive or dialect-agnostic grammar would have to accept either -- or both. I think the question fundamentally comes down to how we feel about parsing `SELECT TOP 10 stuff FROM things LIMIT 11`. That's fine by me, since I _want_ to process anything that looks enough like SQL without caring whether it's T-SQL, PL/SQL, CQL, or even whether it's really runnable. But that's my use case. It's not inconceivable that someone else would prefer to see an error in the `TOP` xor the `LIMIT`, and while they could use a dialect-specialized parsing library like libpg_query, they might have some other reason to prefer tree-sitter.

The dialect purity ship has definitely sailed as far as this grammar is concerned, since I've introduced a fair few Postgresisms over Derek's MySQL base. Is T-SQL too different? Not for me, but maybe for someone.

**Comment by aharpervc** [comment]
> The dialect purity ship has definitely sailed as far as this grammar is concerned, since I've introduced a fair few Postgresisms over Derek's MySQL base. Is T-SQL too different? Not for me, but maybe for someone.

In a world where multiple SQL flavors are mixed into a single grammar, how could you use that to build a linter? Or also, how could you look at a file and detect which flavor it was?

I'm new to tree sitter so maybe there's a built in answer. For example, does the grammar have a concept of "variant" or "flavor", such that parsed nodes could be queried by flavor, and to detection that way?

**Comment by dmfay** [comment]
If you're building a linter or a compatibility detector, you want a strict grammar. But there are other purposes where strictness is less or not important, or even a hindrance. The prototypical case of syntax highlighting is in the less-to-not category (it's certainly debatable exactly where it lands); meanwhile I'm pulling database object info out of anything that looks enough like an SQL statement, so permissivity is an important asset to me and I'd hate to have to work around _n_ strict grammars instead.

I don't believe there is a built-in capability for distinguishing dialects. There aren't too many cases like SQL out there.

**Comment by DerekStride** [comment]
> In a world where multiple SQL flavors are mixed into a single grammar, how could you use that to build a linter? Or also, how could you look at a file and detect which flavor it was?

> I don't believe there is a built-in capability for distinguishing dialects. There aren't too many cases like SQL out there.

The only thing I've seen that is similar is [tree-sitter-typescript](https://github.com/tree-sitter/tree-sitter-typescript). It actually builds on top of the [`tree-sitter-javascript`](https://github.com/tree-sitter/tree-sitter-typescript/blob/49e82b1bce36d6046df911901684cd66b5345d58/common/define-grammar.js#L2). It also defines [two grammar](https://github.com/tree-sitter/tree-sitter-typescript/blob/master/typescript/grammar.js) with-in the project, typescript & tsx.

It *may be possible* to build a base grammar and use it as the foundation for composing other specific grammars dialects.

**Comment by DerekStride** [comment]
This original cause of this issue was fixed in https://github.com/DerekStride/tree-sitter-sql/commit/d54ae82dc56c3c258279738affbb3452aad28368
